name: ModMode
main: iggy.Modmode.Modmode
version: 2.00
description: >
             admin carnage
commands:
  godmode:
    description: become strong enough to deal with your enemies 
  rage:
    description: call fourth the power of the heavens
  open:
    description: opens a players inventory
  walker:
    description: disapear blocks
