name: Economy
main: iggy.Economy.Economy
version: 1.18
description: >
             Simple Economy
commands:
  shop:
    description: buy a block or an item
  price:
    description: price of a block or item
  list:
    description: lists the items you can buy
  money:
    description: shows the money you currently have
  grant:
    description: grants a player money
  fine:
    description: fines a player money
