name: Regions
main: iggy.Regions.Regions
version: 1.26
description: >
             regions for building and protecting your house
commands:
  claim:
    description: claim a plot of land for your own use
  expand:
    description: Expand a claim to another block
  ex:
    description: alias for expand
  dark-expand:
    description: Expand a claim without placing torches
  dx:
    description: alias for dark-expand
  addowner:
    description: add another user to edit
