name: Regions
main: iggy.Regions.Regions
version: 2.9
description: >
             regions for building and protecting your house
commands:
  claim:
    description: claim a plot of land for your own use
  expand:
    description: Expand a claim to another block
    aliases: [ex]
    usage: /<command>
  darkexpand:
    description: Expand a claim without placing torches
    aliases: [dx,dark-expand]
    usage: /<command>
  rename:
    description: Rename the plot you are standing
    alises: [rename-plot]
    usage: /<command> [newName]
  addowner:
    description: Make another player a co-owner of the plot.
    aliases: [ao,add-owner]
    usage: /<command> [newOwner]
  addbuilder:
    description: Add a builder who can build and break blocks on the plot
    aliases: [ab, add-builder]
    usage: /<command> [newBuilder]
  removebuilder:
    description: Remove a builder who can build and break blocks on the plot
    aliases: [rb,remove-builder]
    usage: /<command> [builder]
  unclaimplot:
    description: ADMIN ONLY Unclaim a plot without changing the plot config file
    aliases: [unclaim-plot]
    usage: /<command> 
  listowners:
    description: lists the owners for the plot you specified or the plot you are in
    aliases: [owners,list-owners]
    usage: /<command> [plotName]
  listbuilders:
    description: lists the builders for the plot you specified or the plot you are in
    aliases: [builders,list-builders]
    usage: /<command> [plotName]
