name: Regions
main: iggy.Regions.Regions
version: 1.26
description: >
             regions for building and protecting your house
commands:
  claim:
    description: claim a plot of land for your own use
  expand:
    description: Expand a claim to another block
  ex:
    description: alias for expand
  dark-expand:
    description: Expand a claim without placing torches
  dx:
    description: alias for dark-expand
  add-owner:
    description: add another user to edit the plot
  ao:
    description: alias for add owner
  add-builder:
    description: add a builder who can build and break the plot
  ab:
    description: alias for add builder
  remove-builder:
    description: remove a builder who can build and break the plot
  rb:
    description: alias for remove builder
  unclaim-plot:
    description: admin ability to un-claim a plot
