name: Regions
main: iggy.Regions.Regions
version: 1.14
description: >
             regions for building and protecting your house
commands:
  claim:
    description: Makes blocks not interact with reality
  expand:
    description: Expand a claim to another block
  addowner:
    description: add another user to edit
             
