name: Teleport
main: iggy.Teleport.Teleport
version: 1.37
description: >
             Jumping and Warping
commands:
  warp:
    description: warp to a city you have visited
  createwarp:
    description: Lets an admin create a warp
  forcewarp:
    description: warps a player to a region even if a warp point does not exist
  warplist:
    description: alias for globalWarpList 
  mywarps:
    description: Lists all the warps you have activated
