name: Transport
main: iggy.Transport.Transport
version: 2.9
description: >
             Different modes of transportation
commands:
  warp:
    description: warp to a city you have visited
  spawn:
    description: warp to your bed spawn
  createwarp:
    description: Lets an admin create a warp
  forcewarp:
    description: warps a player to a region even if a warp point does not exist
  warplist:
    description: alias for globalWarpList 
  mywarps:
    description: Lists all the warps you have activated
  fly:
    description: Allows the user to fly for a period of time by sacrificing an item