name: Teleport
main: iggy.Teleport.Teleport
version: 1.36
description: >
             Jumping and Warping
commands:
  warp:
    description: warp to a city you have visited
  createwarp:
    description: Lets an admin create a warp
  refresh:
    description: reloads the world
  re:
    description: alias for refresh
